Repository chandrikadeb7/Face-Mask-Detection, pull requests merged in 2021-01, with the labels that each got.

#65 Add Muthu-Annamalai to README.md
  CODE_OF_CONDUCT.md
  README.md
Labels: DWOC, Level 2

#68 Add Muthu Annamalai
  CONTRIBUTORS.md
  README.md
Labels: DWOC, Level 1

#70 Vilsi12 patch 2
  README.md
  Readme_images/Devscript.jpeg
  Readme_images/Student code-in.png
  Readme_images/nn.jpeg
  Readme_images/sci.jpeg
  Readme_images/winter.jpeg
Labels: DWOC, Level 1

#76 YouTube demo link updated.
  README.md
Labels: SWOC, beginner

#79 Added config file for Welcome BOT
  .github/config.yml
Labels: DWOC, Level 2

#82 Add Issue Template
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/proposal.md
Labels: DWOC, Level 1, SWOC, easy

#83 Created an MIT License for Face-Mask-Detection
  LICENSE
  license.txt
Labels: DWOC, Level 1, SWOC, beginner

#93 Add templates for pull request
  .github/pull_request_template.md
Labels: DWOC, Level 1

#89 Update Web App theme and styling
  app.py
  css/styles.css
Labels: DWOC, easy

#87 Alarm system when No Mask detected
  .DS_Store
  Alarm.wav
  detect_mask_video.py
  requirements.txt
Labels: DWOC, Level 4

#100 Face Mask Detection using ResNet50 v2
  ResNet50_v2/Readme.md
  ResNet50_v2/Readme_images/Graph.png
  ResNet50_v2/Readme_images/Matrix.png
  ResNet50_v2/Readme_images/Output.gif
  ResNet50_v2/Readme_images/output.png
  ResNet50_v2/mask_with_resnet.py
Labels: SWOC, medium

#99 Added Citation Section
  README.md
Labels: DWOC, Level 2

#103 Issue #75 : Insertion of Google Colab link in the readme
  README.md
  Readme_images/Screenshot 2020-06-01 at 9.48.27 PM.PNG
  plot.png
Labels: DWOC, Level 4

#102 Added notification pop up
  CONTRIBUTORS.md
  detect_mask_image.py
  detect_mask_video.py
  images/1.ico
Labels: SWOC, medium

#104 INCEPTION_V3 MODEL VISUALISATION ISSUE#71
  incep_v3_mask_model/images/img1.png
  incep_v3_mask_model/images/img2.png
  incep_v3_mask_model/inception_v3_training.ipynb
  incep_v3_mask_model/readme.md
Labels: SWOC, medium
