Repository chandrikadeb7/Face-Mask-Detection, pull requests merged in 2021-02, with the labels that each got.

#105 Updated contributor's.md file
  CONTRIBUTORS.md
Labels: DWOC, Level 4, SWOC

#107 Added guide to set up project on Windows
  Readme_images/win_cmd.png
  Windows_guide.md
Labels: DWOC, Level 2, SWOC, easy

#108 Added Github Action
  .github/workflows/greetings.yml
Labels: SWOC, easy

#110 Updated number of images in readme of datasets
  README.md
Labels: DWOC, Level 1

#116 Added GitHub action to auto-assign mentor
  .github/auto_assign.yml
  .github/workflows/action.yml
Labels: DWOC, Level 2

#121 Added a 'Cited by' section in README.md file.
  README.md
Labels: DWOC, Level 2

#118 Added Logo
  Logo/facemaskdetection.ai @ 51.06% (CMYK_GPU Preview)  18-02-2021 18_33_18 (2).png
  README.md
Labels: DWOC, Level 3
